object Versions {
    const val gradlePlugin = "7.0.2"
    const val kotlinVersion = "1.5.21"
    const val kotlinGradlePlugin = "1.5.31"

    const val coreKTX = "1.5.0"
    const val appcompat = "1.3.1"
    const val material = "1.3.0"
    const val constraint = "2.1.1"
    const val swipe = "1.1.0"
    const val lifecycle = "2.3.1"
    const val coroutines = "1.3.9"
    const val retrofit = "2.9.0"
    const val gson = "2.8.6"
    const val koin = "2.1.6"
    const val rx = "3.0.13"
    const val rxAndroid = "3.0.0"
    const val rxKotlin = "3.0.1"
    const val roundedImageView = "2.3.0"
    const val glide = "4.12.0"
    const val shimmer = "0.5.0"
    const val room = "2.3.0"
    const val navigation = "2.4.0-alpha10"
    const val hilt = "2.39.1"

    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val expressoCore = "3.4.0"
}
