object Versions {
    const val gradlePlugin = "7.1.2"
    const val kotlinVersion = "1.5.20"
    const val kotlinGradlePlugin = "1.6.20"

    const val coreKTX = "1.7.0"
    const val appcompat = "1.4.1"
    const val material = "1.5.0"
    const val constraint = "2.1.3"
    const val swipe = "1.1.0"
    const val lifecycle = "2.4.1"
    const val coroutines = "1.6.1"
    const val retrofit = "2.9.0"
    const val gson = "2.9.0"
    const val roundedImageView = "2.3.0"
    const val glide = "4.13.1"
    const val shimmer = "0.5.0"
    const val room = "2.4.2"
    const val navigation = "2.4.1"
    const val hilt = "2.40.5"

    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val expressoCore = "3.4.0"
}
